# Generated by Django 4.0.1 on 2022-08-27 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')]),
        ),
    ]
